title: TF1 Keras Cifar10 Partial
list: keras-cifar10
label: 'keras'

image: tensorflow/tensorflow:1.15.2-gpu-py3
build:
    - pip install -e /deepkit-sdk/
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - python -c 'from keras.datasets import cifar10; cifar10.load_data()'
build_files:
    - requirements.txt
    - ../../deepkit:/deepkit-sdk/deepkit
    - ../../setup.py:/deepkit-sdk/setup.py

ignore:
    - 'report.*'
    - saved_models

#docker:
#    env:
#        - PYTHONPATH=/deepkit-sdk

output: saved_models

resources:
    minCpu: 2
    minMemory: 2

config:
    lr: 0.8
    batch_size: 128
    epochs: 15
    train_samples: 60000
    test_samples: 10000

command: python model.py